version: '3.8'

services:
  quantumca:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    volumes:
      - ./data:/app/data
      - ./configs:/app/configs
    environment:
      - PORT=8080
      - DATABASE_PATH=/app/data/database.db
      - KEYS_PATH=/app/data/keys
      - CERTIFICATES_PATH=/app/data/certificates
      - OCSP_PORT=8081
    restart: unless-stopped