version: '3.8'

services:
  quantumca-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: quantumca-backend
    restart: unless-stopped
    ports:
      - "8080:8080"
      - "8081:8081"
      - "9090:9090"
    environment:
      - ENV=production
      - DB_PATH=/app/data/quantumca.db
      - LOG_LEVEL=info
      - SERVER_PORT=8080
      - HEALTH_PORT=8081
      - METRICS_PORT=9090
      - JWT_SECRET=${JWT_SECRET:-your-jwt-secret-change-this}
      - ENCRYPTION_KEY=${ENCRYPTION_KEY:-your-encryption-key-change-this}
    volumes:
      - quantumca-data:/app/data
      - quantumca-backups:/app/backups
      - quantumca-logs:/app/logs
    networks:
      - quantumca-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  quantumca-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: quantumca-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8080/api/v1
      - REACT_APP_HEALTH_URL=http://localhost:8081
      - NODE_ENV=production
    depends_on:
      quantumca-backend:
        condition: service_healthy
    networks:
      - quantumca-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  # Optional: Reverse proxy (uncomment if needed)
  # nginx-proxy:
  #   image: nginx:alpine
  #   container_name: quantumca-proxy
  #   restart: unless-stopped
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - ./nginx-proxy.conf:/etc/nginx/conf.d/default.conf:ro
  #     - ./ssl:/etc/nginx/ssl:ro
  #   depends_on:
  #     - quantumca-frontend
  #     - quantumca-backend
  #   networks:
  #     - quantumca-network

networks:
  quantumca-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

volumes:
  quantumca-data:
    driver: local
  quantumca-backups:
    driver: local
  quantumca-logs:
    driver: local