services:
  quantumca-backend:
    build:
      context: ../../backend
      dockerfile: Dockerfile
    container_name: quantumca-backend
    restart: unless-stopped
    ports:
      - "8080:8080"
      - "8081:8081"
      - "9090:9090"
    environment:
      - ENVIRONMENT=development
      - LOG_LEVEL=info
      - API_PORT=8080
      - OCSP_PORT=8081
      - METRICS_PORT=9090
      - DATABASE_PATH=/app/data/quantumca.db
      - DATABASE_MAX_CONNECTIONS=25
      - DATABASE_MAX_IDLE_CONNECTIONS=5
      - KEY_ENCRYPTION_ENABLED=true
      - DOMAIN_VALIDATION_REQUIRED=true
      - CERTIFICATE_CHAIN_VALIDATION=true
      - TLS_ENABLED=false
      - FIPS_MODE=false
      - COMPLIANCE_MODE=false
      - ENABLE_MULTI_PQC=true
      - MIN_SECURITY_LEVEL=128
      - KEYS_PATH=/app/keys
      - CERTIFICATES_PATH=/app/data/certificates
      - BACKUP_PATH=/app/backups
      - LOGS_PATH=/app/logs
      - JWT_SECRET=${JWT_SECRET:-}
      - ROOT_CA_PASSPHRASE=${ROOT_CA_PASSPHRASE:-}
      - INTERMEDIATE_CA_PASSPHRASE=${INTERMEDIATE_CA_PASSPHRASE:-}
      - BACKUP_ENCRYPTION_PASSWORD=${BACKUP_ENCRYPTION_PASSWORD:-}
      - API_RATE_LIMIT=100
      - API_RATE_BURST=50
      - MAX_REQUEST_SIZE=10485760
      - CERTIFICATE_VALIDITY_DAYS=365
      - INTERMEDIATE_CA_VALIDITY_DAYS=1825
      - ROOT_CA_VALIDITY_DAYS=7300
      - MAX_CERTIFICATES_PER_CUSTOMER=1000
      - CERTIFICATE_RENEWAL_DAYS=30
      - BACKUP_ENABLED=true
      - BACKUP_INTERVAL=24h
      - BACKUP_RETENTION_DAYS=30
      - METRICS_ENABLED=true
      - HEALTH_CHECK_INTERVAL=30s
      - DOMAIN_VALIDATION_TIMEOUT=5m
      - READ_TIMEOUT=30s
      - WRITE_TIMEOUT=30s
      - IDLE_TIMEOUT=120s
      - GRACEFUL_SHUTDOWN_TIMEOUT=30s
    volumes:
      - ../../backend/data:/app/data
      - ../../backend/data/keys:/app/keys
      - ../../backend/data/backups:/app/backups
      - ../../backend/data/logs:/app/logs
    networks:
      - quantumca-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  quantumca-frontend:
    build:
      context: ../../quantumca-web
      dockerfile: Dockerfile
      args:
        - REACT_APP_API_URL=http://localhost:8080/api/v1
        - REACT_APP_HEALTH_URL=http://localhost:8080
        - REACT_APP_OCSP_URL=http://localhost:8081
        - NODE_ENV=production
        - GENERATE_SOURCEMAP=false
    container_name: quantumca-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      quantumca-backend:
        condition: service_healthy
    networks:
      - quantumca-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

networks:
  quantumca-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
          gateway: 172.20.0.1